insert into public.publications(slug, title, authors, year, venue, publication_type, status, doi, external_url, featured) values
('social-innovation-collaborative-competence-sustainable-business', 'Social innovation: A mediator between collaborative competence and sustainable business practices', '["Kintu, G. J.", "Kizito, R. D.", "Sekitoleko, E."]', 2023, 'Journal of Business and Management Sciences, 11(2), 161–168', 'journal_article', 'published', '10.12691/jbms-11-2-5', 'https://doi.org/10.12691/jbms-11-2-5', true),
('entrepreneurial-intentions-family-business-generational-transfers', 'Entrepreneurial intentions and family business generational transfers: The mediating role of re-organization among small and medium enterprises', '["Mayanja, S. S.", "Kizito, R. D.", "Mutebi, H.", "Zombeire, R. K."]', 2024, 'IIMBG Journal of Sustainable Business and Innovation, 2(2), 163–185', 'journal_article', 'published', '10.1108/IJSBI-03-2024-0016', 'https://doi.org/10.1108/IJSBI-03-2024-0016', true),
('psychological-contract-succession-planning-family-businesses', 'Psychological contract and succession planning among small and medium family-owned businesses in Uganda', '["Kizito, R. D.", "Matama, R.", "Bagire, V.", "Nabeta, I. N.", "Kyazze, L."]', 2025, 'Cureus Journal of Business and Economics, 2, es44404-025-06422-0', 'journal_article', 'published', '10.7759/s44404-025-06422-0', 'https://doi.org/10.7759/s44404-025-06422-0', true),
('family-embeddedness-intergenerational-transfers-reorganization', 'Family embeddedness and intergenerational transfers: The mediating role of reorganization among small and medium family-owned enterprises', '["Mayanja, S. S.", "Nkambwe, I.", "Kizito, R. D.", "Nankabirwa, A."]', 2026, 'Cogent Business & Management, 13(1), Article 2607775', 'journal_article', 'published', '10.1080/23311975.2025.2607775', 'https://doi.org/10.1080/23311975.2025.2607775', false),
('demonstrating-entrepreneurial-success-storytelling-ugandan-microentrepreneurs', 'Demonstrating entrepreneurial success: A storytelling approach among Ugandan microentrepreneurs', '["Iga, D.", "Mayanja, S. S.", "Byarugaba, J. M.", "Kizito, R. D."]', 2026, 'Strategic Business Research, 2(1), Article 100108', 'journal_article', 'published', '10.1016/j.sbr.2026.100108', 'https://doi.org/10.1016/j.sbr.2026.100108', false),
('entrepreneurial-alertness-intergenerational-transfers', 'Entrepreneurial alertness and intergenerational transfers among family-owned businesses in Uganda: The mediating role of family embeddedness', '["Nkambwe, I.", "Mayanja, S. S.", "Kizito, R. D.", "Nankabirwa, A."]', 2026, 'Strategic Business Research, 2, Article 100178', 'journal_article', 'published', '10.1016/j.sbr.2026.100178', 'https://doi.org/10.1016/j.sbr.2026.100178', false),
('entrepreneurial-bricolage-qualitative-analysis', 'Entrepreneurial bricolage: A qualitative analysis of microentrepreneurs in an African context', '["Iga, D.", "Ssekajja, M. S.", "Kizito, R. D.", "Musoke, D. H. B."]', 2026, 'Under review in Cogent Business & Management', 'manuscript', 'under_review', null, null, false),
('amplifying-succession-planning-storytelling', 'Amplifying succession planning in small and medium family-owned enterprises in Uganda: A storytelling approach in an African family enterprise context', '["David Kizito, R.", "Bagire, V.", "Nabeeta, D. I. N.", "Kyazze, D. L."]', 2026, 'Under review in Strategic Business Research', 'manuscript', 'under_review', null, null, false),
('entrepreneurial-orientation-succession-planning', 'Entrepreneurial orientation and succession planning among small and medium family-owned businesses in Uganda', '["Kizito, R. D.", "Matama, R.", "Bagire, V.", "Nabeeta, I. N.", "Kyazze, L."]', 2025, 'Under review in Cogent Business & Management', 'manuscript', 'under_review', null, null, false),
('entrepreneurial-actions-succession-planning-family-businesses', 'Entrepreneurial actions and succession planning in family businesses in Uganda', '["Kizito, R. D."]', 2026, 'Global Edit, July 2026', 'book', 'published', null, 'https://www.morebooks.shop/gb/translation_bundle_05640038a40', true)
on conflict (slug) do update set title = excluded.title, authors = excluded.authors, year = excluded.year, venue = excluded.venue, publication_type = excluded.publication_type, status = excluded.status, doi = excluded.doi, external_url = excluded.external_url, featured = excluded.featured;

-- Create an administrator by inserting the Auth user's id into user_roles:
-- insert into public.user_roles(user_id, role) values ('AUTH_USER_UUID', 'admin');
