"use client";

import { useEffect, useState } from "react";
import { publications as seed, type Publication } from "@/lib/content";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

const blank: Publication = { id: "", slug: "", title: "", authors: [], year: new Date().getFullYear(), venue: "", publicationType: "journal_article", status: "published" };
export function AdminPublicationsPanel() {
  const [items, setItems] = useState<Publication[]>(seed); const [form, setForm] = useState<Publication>(blank); const [message, setMessage] = useState(""); const client = createSupabaseBrowserClient();
  useEffect(() => { if (!client) return; client.from("publications").select("*").order("year", { ascending: false }).then(({ data }) => { if (data?.length) setItems(data.map((row) => ({ id: String(row.id), slug: String(row.slug), title: String(row.title), authors: Array.isArray(row.authors) ? row.authors.map(String) : [], year: Number(row.year), venue: String(row.venue ?? ""), publicationType: row.publication_type, status: row.status, doi: row.doi ?? undefined, isbn: row.isbn ?? undefined, externalUrl: row.external_url ?? undefined, featured: Boolean(row.featured) }))); }); }, [client]);
  function update(key: keyof Publication, value: string | number | boolean | string[]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!client) return setMessage("Connect Supabase before saving live content."); const payload = { slug: form.slug, title: form.title, authors: form.authors, year: Number(form.year), venue: form.venue, publication_type: form.publicationType, status: form.status, doi: form.doi || null, isbn: form.isbn || null, external_url: form.externalUrl || null, featured: Boolean(form.featured) }; const result = form.id ? await client.from("publications").update(payload).eq("id", form.id) : await client.from("publications").insert(payload); if (result.error) return setMessage(result.error.message); setMessage("Publication saved."); setForm(blank); const { data } = await client.from("publications").select("*").order("year", { ascending: false }); if (data) window.location.reload(); }
  async function remove(id: string) { if (!client || !confirm("Delete this publication?")) return; await client.from("publications").delete().eq("id", id); setItems(items.filter((item) => item.id !== id)); }
  return <div className="split"><div><h2>Catalogue</h2><table className="admin-table"><thead><tr><th>Work</th><th>Year</th><th>Status</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><br /><span className="muted">{item.venue}</span></td><td>{item.year}</td><td>{item.status}</td><td><button className="text-link" onClick={() => setForm(item)}>Edit</button><button className="text-link" onClick={() => remove(item.id)}>Delete</button></td></tr>)}</tbody></table></div><form className="admin-form" onSubmit={save}><h2>{form.id ? "Edit publication" : "Add publication"}</h2><label>Title<input className="admin-input" value={form.title} onChange={(e) => update("title", e.target.value)} required /></label><label>Slug<input className="admin-input" value={form.slug} onChange={(e) => update("slug", e.target.value)} required /></label><label>Authors, separated by commas<input className="admin-input" value={form.authors.join(", ")} onChange={(e) => update("authors", e.target.value.split(",").map((item) => item.trim()).filter(Boolean))} /></label><div className="form-row"><label>Year<input className="admin-input" type="number" value={form.year} onChange={(e) => update("year", Number(e.target.value))} /></label><label>Type<select className="admin-input" value={form.publicationType} onChange={(e) => update("publicationType", e.target.value)}><option value="journal_article">Journal article</option><option value="book">Book</option><option value="manuscript">Manuscript</option></select></label></div><label>Journal or publisher<input className="admin-input" value={form.venue} onChange={(e) => update("venue", e.target.value)} /></label><label>Status<select className="admin-input" value={form.status} onChange={(e) => update("status", e.target.value)}><option value="published">Published</option><option value="under_review">Under review</option></select></label><label>DOI<input className="admin-input" value={form.doi ?? ""} onChange={(e) => update("doi", e.target.value)} /></label><label>External link<input className="admin-input" value={form.externalUrl ?? ""} onChange={(e) => update("externalUrl", e.target.value)} /></label><div><button className="button" type="submit">Save publication</button> <button className="text-link" type="button" onClick={() => setForm(blank)}>Clear</button></div>{message && <p className="form-status">{message}</p>}</form></div>;
}
